# Generated by Django 5.0.4 on 2024-05-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.png', upload_to='profiles')),
                ('bio', models.TextField(blank=True, default='Update your Bio...')),
                ('phone_number', models.CharField(default='+555895234', max_length=13)),
                ('married', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FIMALE', 'Fimale'), ('OTHERS', 'Others')], default='Male', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
