# Generated by Django 5.0.4 on 2024-05-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_author_book_authors_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
