# Generated by Django 5.0.4 on 2024-05-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
