# Generated by Django 5.2 on 2025-04-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_book_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
